# Estágio 1: Build da aplicação usando Maven
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
COPY pom.xml .
RUN mvn dependency:go-offline
RUN mvn clean package -DskipTests

# Estágio 2: Execução da aplicação (Imagem leve)
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]